name: Build and Publish Python Wheels

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Windows Build Tools
        if: runner.os == 'Windows'
        run: choco install -y visualstudio2019buildtools

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "*-win32"
          CIBW_BUILD_VERBOSITY: "3"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/

  gather_wheels:
    name: Gather wheels from all platforms
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist/

      - name: Merge wheels into one folder
        run: |
          mkdir -p merged_dist
          find dist -type f -name "*.whl" -exec cp {} merged_dist/ \;
          find dist -type f -name "*.tar.gz" -exec cp {} merged_dist/ \;

      - name: Upload merged wheels
        uses: actions/upload-artifact@v4
        with:
          name: merged-wheels
          path: merged_dist/

  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: gather_wheels
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve merged wheels
        uses: actions/download-artifact@v4
        with:
          name: merged-wheels
          path: dist/

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
